// Generated by CoffeeScript 1.8.0
'use strict';
var moduleVotacion;

moduleVotacion = angular.module('moduleVotacion', []);

moduleVotacion.controller('VotacionCtrl', [
  '$scope',
	function ($scope) {
		$scope.votacion = configVotation;
		$scope.metodoVotacion = $('#metodoVotacion');
		var opening = $('#openTime');
		var ending = $('#closeTime');
		var stars = $('#pesoDeEstrella');
		var proyectos = $('#cantidadProyectos');
		var metodo = $('#metodoVotacion');
		$scope.cantidadProyectos =
			$scope.validar = function () {
				if (ending.val() > opening.val()) {
					// alert('El formulario es valido');
					var votacionNueva = {};
					votacionNueva.fechaInicio = opening.val();
					votacionNueva.fechaCierre = ending.val();
					votacionNueva.estrellas = stars.val();
					votacionNueva.cantidadProyectos = proyectos.val();
					votacionNueva.metodoDeVotacion = metodo.val();
					//Agregado al arreglo
					configVotation.push(votacionNueva);
					//Borrado
					//					votacionNueva.fechaInicio = opening.val();
					ending.val('');
					stars.val('');
					proyectos.val('');
					metodo.val('');
				}
		}
  }
]);

var configVotation = [
	{
		fechaInicio: '13.02.2015',
		fechaCierre: '24.03.2015',
		estrellas: 5,
		cantidadProyectos: 5,
		metodoDeVotacion: 'Enlace'
}];