// Generated by CoffeeScript 1.8.0
'use strict';
var moduleVotacion;

moduleVotacion = angular.module('moduleVotacion', []);

moduleVotacion.controller('VotacionCtrl', [
  '$scope', function($scope) {
    $scope.method = 'none';
    $scope.fechaInicial = jQuery('#inpFechaInicio');
    $scope.fechaFinal = jQuery('#inpFechaCierre');
    $scope.setVote = function(method) {
      switch (method) {
        case 'email':
          console.log("El metodo es " + method);
          break;
        case 'link':
          console.log("El metodo es " + method);
          break;
        default:
          console.log("No haz escodigo methodo");
      }
    };
    $scope.validar = function() {
      if ($scope.fechaFinal.val() > $scope.fechaInicial.val()) {
        alert("Aleluya Hermanos");
      } else {
        alert("Pero que mierda");
      }
    };
  }
]);
