// Generated by CoffeeScript 1.8.0
'use strict';
var moduleVotacion;

moduleVotacion = angular.module('moduleVotacion', []);

moduleVotacion.controller('VotacionCtrl', [
  '$scope',
	function ($scope) {
		$scope.votacion = configVotation;
		$scope.metodo = 'No has selecionado metodo de votación';
		$scope.fechaInicial = jQuery('#inpFechaInicio');
		$scope.fechaFinal = jQuery('#inpFechaCierre');
		$scope.cantidadProyectos = jQuery('#amountProjects');
		$scope.estrellas = jQuery('#stars');
		$scope.metodoVotacion = jQuery('#metodoVoto');

		$scope.validar = function () {
			if ($scope.fechaFinal.val() > $scope.fechaInicial.val()) {
				var vote = {};
				vote.fechaInicio = $scope.fechaInicial.val();
				vote.fechaCierre = $scope.fechaFinal.val();
				vote.estrellas = $scope.estrellas.val();
				vote.cantidadProyectos = $scope.cantidadProyectos.val();
				vote.metodoDeVotacion = $scope.metodoVotacion.val();
				configVotation.push(vote);
			}
		};
  }
]);

var configVotation = [
	{
		fechaInicio: '13.02.2015',
		fechaCierre: '24.03.2015',
		estrellas: 5,
		cantidadProyectos: 5,
		metodoDeVotacion: 'Enlace'
}];